### ISSUE TITLE
Error - INT_912

### ISSUE THREAD

**Issue by NigsonNeves** [lyra/embedded-form-glue#193]
Hi, I'm actually running into a problem and I can't figure out where the problem is coming from.
The SDK was working fine until I ran into a INT_912 error telling me that the password doesn't match the transaction ID. 

Any idea on how can I solve this ?

**Comment by NigsonNeves** [comment]
Hi,

We manage to solve the problem, it was not a problem related to the package.
We had a problem with our authorization token created from our back-end :)

Since this topic is open, I may have an another question, is it possible to manage wich parameter will be send on the 'kr-get-url-success' ? Because sometimes I'm getting an HTTP Error 431 on the redirection since all the json response is send in the url, has a parameter.

Thanks in advance for your help and have a wonderful day :)

**Comment by s-yagues** [comment]
Hi @NigsonNeves ,

Thanks for reaching in. I'm afraid the params sent in the `kr-get-url-success` redirection are not configurable. If it works better for you, you can use `kr-post-url-sucess` instead. Either way the error HTTP 431 is due to the headers length not the URL, so maybe this is not what's causing it.

**Comment by NigsonNeves** [comment]
Thank you very much for your help :)

Have a nice day
